### ISSUE TITLE
Make it easier to test canary functionality by reducing production weights

### ISSUE THREAD

**Issue by MFatigati** [Sentinel-PaaS/Sentinel-CLI#5]
Just for now, this makes it easier to make sure everything is work:

```
http:
  services:
    canary:
      weighted:
        services:
          - name: production_svc@docker
            weight: 2
          - name: canary_svc@docker
            weight: 1
```
